# The AMQP broker location and credentials
amqp-host=localhost
amqp-port=5672
amqp-username=quarkus
amqp-password=quarkus

quarkus.debug.port=5009
%dev.quarkus.http.port=9003

# Configuring the incoming channel (reading from AMQP)
mp.messaging.incoming.validate-person-in.connector=smallrye-amqp
mp.messaging.incoming.validate-person-in.address=validate_person_q

# Configuring the outgoing channel (writing to AMQP)
mp.messaging.outgoing.validate-person-out.connector=smallrye-amqp
mp.messaging.outgoing.validate-person-out.address=validate_person_q

com.redhat.consulting.service.PessoaRemoteResource/mp-rest/url=http://localhost:9000 
person-remote-service.url=http://localhost:9000