# Prod profile
%prod.quarkus.http.port=8080
%prod.quarkus.datasource.db-kind=mysql
%prod.quarkus.datasource.username=${MYSQL_USERNAME_ENV}
%prod.quarkus.datasource.password=${MYSQL_PASSWORD_ENV}
%prod.quarkus.datasource.jdbc.url=jdbc:mysql://mysql:3306/pessoadb

%prod.verify.person.url=http://camel-quarkus-soap-camel-quarkus-demo.apps.cluster-gclkf.gclkf.sandbox129.opentlc.com/verify/person

# Dev profile
%dev.quarkus.http.port=9000
%dev.quarkus.datasource.db-kind=mysql
%dev.quarkus.datasource.username=admin
%dev.quarkus.datasource.password=admin
%dev.quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/pessoadb

%dev.verify.person.url=http://localhost:9100/verify/person
#%dev.verify.person.url=http://camel-quarkus-soap-camel-quarkus-demo.apps.cluster-gclkf.gclkf.sandbox129.opentlc.com/verify/person

# The AMQP broker location and credentials
amqp-host=localhost
amqp-port=5672
amqp-username=quarkus
amqp-password=quarkus

# Configuring the incoming channel (reading from AMQP)
mp.messaging.incoming.movies-in.connector=smallrye-amqp
mp.messaging.incoming.movies-in.address=movies

# Configuring the outgoing channel (writing to AMQP)
mp.messaging.outgoing.movies-out.connector=smallrye-amqp
mp.messaging.outgoing.movies-out.address=movies

quarkus.log.level=INFO
quarkus.log.category."org.hibernate".level=INFO