package com.redhat.consulting.demo.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-08-11T20:28:45.596-03:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "ValidatorWebServiceService",
                  wsdlLocation = "classpath:wsdl/validator.wsdl",
                  targetNamespace = "http://soap.demo.consulting.redhat.com/")
public class ValidatorWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.demo.consulting.redhat.com/", "ValidatorWebServiceService");
    public final static QName ValidatorWebServicePort = new QName("http://soap.demo.consulting.redhat.com/", "ValidatorWebServicePort");
    static {
        URL url = ValidatorWebServiceService.class.getClassLoader().getResource("wsdl/validator.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ValidatorWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/validator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidatorWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidatorWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidatorWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ValidatorWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ValidatorWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ValidatorWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ValidatorWebService
     */
    @WebEndpoint(name = "ValidatorWebServicePort")
    public ValidatorWebService getValidatorWebServicePort() {
        return super.getPort(ValidatorWebServicePort, ValidatorWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidatorWebService
     */
    @WebEndpoint(name = "ValidatorWebServicePort")
    public ValidatorWebService getValidatorWebServicePort(WebServiceFeature... features) {
        return super.getPort(ValidatorWebServicePort, ValidatorWebService.class, features);
    }

}
