package com.redhat.consulting.demo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-05-16T17:33:17.255-03:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://soap.demo.consulting.redhat.com/", name = "ValidatorWebService")
@XmlSeeAlso({ObjectFactory.class, com.redhat.consulting.generated.soap.model.types.ObjectFactory.class})
public interface ValidatorWebService {

    @WebMethod
    @RequestWrapper(localName = "validateDocument", targetNamespace = "http://soap.demo.consulting.redhat.com/", className = "com.redhat.consulting.demo.soap.ValidateDocument")
    @ResponseWrapper(localName = "validateDocumentResponse", targetNamespace = "http://soap.demo.consulting.redhat.com/", className = "com.redhat.consulting.demo.soap.ValidateDocumentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.redhat.consulting.generated.soap.model.types.DocumentResponse validateDocument(

        @WebParam(name = "request", targetNamespace = "")
        com.redhat.consulting.demo.soap.DocumentRequest request
    );
}
